#!/bin/bash

mkdir kraken_outputs/
mkdir SILVA_DB

curl -L https://figshare.com/ndownloader/files/40054801 -o SILVA_DB/database50mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054804 -o SILVA_DB/database75mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054807 -o SILVA_DB/database100mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054810 -o SILVA_DB/database150mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054813 -o SILVA_DB/database200mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054816 -o SILVA_DB/database250mers.kmer_distrib
curl -L https://figshare.com/ndownloader/files/40054819 -o SILVA_DB/hash.k2d
curl -L https://figshare.com/ndownloader/files/40054822 -o SILVA_DB/opts.k2d
curl -L https://figshare.com/ndownloader/files/40054825 -o SILVA_DB/README.md
curl -L https://figshare.com/ndownloader/files/40054828 -o SILVA_DB/taxo.k2d

# Install CRAN packages into the conda R ---
# Use the R inside the conda env (available because environment.yml installed r-base)
R -e "options(repos='https://cloud.r-project.org'); install.packages(c('microeco','file2meco'))"

# Smoke test: fail the build if they didn’t install
R -q -e "stopifnot(requireNamespace('microeco', quietly=TRUE)); stopifnot(requireNamespace('file2meco', quietly=TRUE))"
